# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data_to_load = "../output_data/cities.csv"
weather_data = pd.read_csv(weather_data_to_load)
cleaned_weather_data = weather_data.dropna()
del cleaned_weather_data["City_ID"]
cleaned_weather_data.head(20)

,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,ostrovnoy,2,RU,1558378754,72,68.05,39.51,37.50,7.16
1,mahebourg,75,MU,1558378503,74,-20.41,57.70,78.80,11.41
2,qaanaaq,25,GL,1558378755,73,77.48,-69.36,22.20,2.37
3,zhuhai,0,CN,1558378755,39,40.71,112.04,44.60,4.47
4,cape town,20,ZA,1558378755,76,-33.93,18.42,55.99,8.05
5,atuona,78,PF,1558378755,76,-9.80,-139.03,81.96,16.49
6,flinders,0,AU,1558378755,62,-34.58,150.85,60.01,11.41
8,tiksi,95,RU,1558378756,88,71.64,128.87,14.10,15.70
9,pushkinskiye gory,6,RU,1558378756,70,57.02,28.91,65.04,6.93
10,aykhal,90,RU,1558378756,48,65.95,111.51,39.20,11.18
11,castro,0,CL,1558378756,70,-42.48,-73.76,48.20,9.17
12,avarua,100,CK,1558378756,94,-21.21,-159.78,71.60,2.24
13,saskylakh,0,RU,1558378757,91,71.97,114.09,4.92,2.26
14,constitucion,5,MX,1558378757,4,23.99,-104.67,84.20,16.11
15,albany,40,US,1558378727,45,42.65,-73.75,82.40,12.75
16,vilyuysk,16,RU,1558378757,59,63.75,121.63,34.62,5.84
17,ushuaia,75,AR,1558378606,75,-54.81,-68.31,44.60,36.91
18,bambous virieux,75,MU,1558378758,74,-20.34,57.76,78.80,11.41
19,kodinsk,14,RU,1558378758,81,58.60,99.18,48.84,4.97
20,teknaf,1,BD,1558378758,85,20.86,92.31,84.66,8.23

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

locations = cleaned_weather_data[["Lat", "Lng"]].astype(float)
humidity = cleaned_weather_data["Humidity"].astype(float)

In [4]:
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=6)
fig = gmaps.figure()
fig.add_layer(heat_layer)
plt.savefig("VacationPy_Fig3")
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
ideal_spot = pd.DataFrame(cleaned_weather_data, columns = ['Country',"City","Max Temp", "Wind Speed", "Cloudiness",'Lat','Lng','Humidity'])
max_temp = (ideal_spot["Max Temp"] <= 80) & (ideal_spot["Max Temp"] >= 70)
wind_speed = ideal_spot["Wind Speed"] < 10
cloudiness = ideal_spot["Cloudiness"] == 0
ideal_spot = ideal_spot[max_temp & wind_speed & cloudiness]
ideal_spot = ideal_spot.reset_index()
del ideal_spot["index"]
ideal_spot

,Country,City,Max Temp,Wind Speed,Cloudiness,Lat,Lng,Humidity
0,BR,ponta do sol,73.68,5.32,0,-20.63,-46.00,57
1,BR,cidreira,76.56,5.50,0,-30.17,-50.22,66
2,MG,morondava,79.08,9.06,0,-20.30,44.28,69
3,IN,vaini,78.90,1.59,0,15.34,74.49,88
4,MA,nador,75.20,6.93,0,35.17,-2.93,40
5,MM,mogok,72.24,2.77,0,22.92,96.51,51
6,IR,birjand,71.60,9.17,0,32.86,59.22,26

In [6]:
vacation_locations = ideal_spot[["Lat", "Lng"]].astype(float)
vacation_humidity = ideal_spot["Humidity"].astype(float)
vacation_fig = gmaps.figure()
vacation_heat_layer = gmaps.heatmap_layer(vacation_locations, weights=vacation_humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=10)

vacation_fig.add_layer(vacation_heat_layer)
plt.savefig("VacationPy_Fig1")
vacation_fig

Figure(layout=FigureLayout(height='420px'))

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
cities = list(ideal_spot["City"])
cities

['ponta do sol', 'cidreira', 'morondava', 'vaini', 'nador', 'mogok', 'birjand']

In [8]:
g_key

'AIzaSyDVkcwT92OuDTFVr4yTvi8AdWTrRZnUx7M'

In [93]:
ideal_spot

,Country,City,Max Temp,Wind Speed,Cloudiness,Lat,Lng,Humidity,Nearest Hotel
0,BR,ponta do sol,73.68,5.32,0,-20.63,-46.00,57,None
1,BR,cidreira,76.56,5.50,0,-30.17,-50.22,66,None
2,MG,morondava,79.08,9.06,0,-20.30,44.28,69,None
3,IN,vaini,78.90,1.59,0,15.34,74.49,88,None
4,MA,nador,75.20,6.93,0,35.17,-2.93,40,None
5,MM,mogok,72.24,2.77,0,22.92,96.51,51,None
6,IR,birjand,71.60,9.17,0,32.86,59.22,26,None

In [94]:
ideal_spot.iloc[1]['Lat']

-30.17

In [137]:
ideal_spot_df =ideal_spot.groupby(['City']).sum()
ideal_spot_df

              Max Temp  Wind Speed  Cloudiness    Lat    Lng  Humidity
City
birjand          71.60        9.17           0  32.86  59.22        26
cidreira         76.56        5.50           0 -30.17 -50.22        66
mogok            72.24        2.77           0  22.92  96.51        51
morondava        79.08        9.06           0 -20.30  44.28        69
nador            75.20        6.93           0  35.17  -2.93        40
ponta do sol     73.68        5.32           0 -20.63 -46.00        57
vaini            78.90        1.59           0  15.34  74.49        88

In [139]:
hotels = []
for city in ideal_spot['City']:
    latitude = ideal_spot_df[city]['Lat']
    longitude = ideal_spot_df[city]['Lng']
    params = {
        "location": f"{latitude},{longitude}", 
        "keyword": "hotel",
        "key": g_key,
        "radius":5000
    }
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    hotel_request = requests.get(base_url, params=params)
    hotel_response = hotel_request.json()
    try:
        hotels.append(hotel_response["results"]["name"])
    except:
        hotels.append(print(hotel_response))
        pass
ideal_spot["Nearest Hotel"] = hotels
ideal_spot

KeyError: 'ponta do sol'

In [82]:
latitude

NameError: name 'latitude' is not defined

In [83]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Nearest Hotel}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in ideal_vacationspot_indexed.iterrows()]
locations = ideal_vacationspot_indexed[["Lat", "Lng"]]

NameError: name 'ideal_vacationspot_indexed' is not defined

In [84]:
markers = gmaps.marker_layer(locations, info_box_content= [f"Nearest Hotel: {hotel}" for hotel in hotels])
vacation_fig.add_layer(markers)
vacation_fig
plt.savefig("Vacation_Fig2")

IndexError: list index out of range